### ISSUE TITLE
Logging every Update()

### ISSUE THREAD

**Issue by testpushpleaseignore** [appuns/DSPStationInfo#1]
When you have time, could you reduce the amount of logging that you are doing for this mod? Thanks in advance!

**Comment by appuns** [comment]
thanks for your suggestion!
I rebuilded the mod.
try this and report please.
https://drive.google.com/file/d/1_juNfWahQCyWTRcDyAiKxQTAVY9aBn6m/view?usp=sharing

**Comment by testpushpleaseignore** [comment]
Yeah that looks a lot better - thanks for the quick response and fix!
