### ISSUE TITLE
Incorrect items in 4.2

### ISSUE THREAD

**Issue by Stalkie** [appuns/DSPStationInfo#2]
Hi,
Thanks for a nice mod. However i noticed that the item labels was incorrect in 4.2.
The small stations seems to display 5 slots with random items, even though they only have 3 slots.
It works fine in 4.1.
![bild](https://user-images.githubusercontent.com/26777760/150971782-8af3c726-a820-48d7-9b28-f86f4e299bcc.png)

**Comment by NSADrone** [comment]
Seeing same issue with similar UI glitch after update this morning. In very dense areas UI will fluctuate with different items appearing in slots 4, and 5 for PLS, also seeing UI glitch on Advanced Mining Machine and on Orbital Collectors.

Confirmed rolling back to 0.4.1 resolves issues and no other issues appeared.

**Comment by appuns** [comment]
Thanks for the info!
I fixed and released.
Check it.

**Comment by NSADrone** [comment]
Issues seem to be resolved with 0.4.3. Updated this morning and checked PLS, Advanced Mining Machine and Orbital Collector, and no issues.
