### ISSUE TITLE
Only 5 of 6 items displayed.

### ISSUE THREAD

**Issue by JamieRCHI** [appuns/DSPStationInfo#4]
The maxInfo value is set to the default of 20 in the config file.
The box appears to be set to show 6 items, but the last one is blank.

I do not have the GigaStationsUpdated mod enabled.

I do have the mod BetterLogisticsStations mod enabled and set to the default of 6 for both Planetary and Intersteller Logistics stations. 

Could there be a conflict with this mod? It has not been updated for about a year.

Edit: Just found out that with the GigaStationsUpdated mod enabled, I can see all 6 items as expected to all logistic stations. Enabling the BetterLogisticsStations allows me to have the regular Planetary Logistic Stations with 6 slots without having to make the more expensive Planetary GigaStation.

**Comment by appuns** [comment]
maxInfo is an option of how many information windows to display.
new version support BetterLogisticsStations too.
check it.

**Comment by JamieRCHI** [comment]
Thank you. Works good.
